# Generated by Django 5.0.6 on 2024-06-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_fbv_admin', '0005_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default='jempol.jpeg', upload_to='covers'),
        ),
    ]
