# Generated by Django 5.0.6 on 2024-06-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_fbv_admin', '0006_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='covers'),
        ),
    ]
